-- ============================================================
-- Kello Full Schema — Supabase SQL Editor에서 한 번에 실행
-- 순서: Extensions → Enum → Core Tables → Domain Tables → RLS → Functions/Triggers → Storage
-- ============================================================

-- ============================================================
-- 1. Extensions
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 2. Custom Types
-- ============================================================
DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('admin', 'super_admin');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- 3. profiles
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id             UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role           app_role,
  is_admin       BOOLEAN     NOT NULL DEFAULT false,
  display_name   TEXT,
  phone          TEXT,
  avatar_url     TEXT,
  avatar_path    TEXT,
  sns            TEXT,
  referral_code  TEXT        UNIQUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can update own profile" ON public.profiles;
CREATE POLICY "Authenticated users can update own profile"
  ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- ============================================================
-- 4. community_posts
-- ============================================================
CREATE TABLE IF NOT EXISTS public.community_posts (
  id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author         TEXT        NOT NULL,
  flag           TEXT        NOT NULL,
  type           TEXT        NOT NULL,
  title          TEXT        NOT NULL,
  "desc"         TEXT        NOT NULL,
  time           TEXT        NOT NULL,
  comments       INTEGER     NOT NULL DEFAULT 0,
  likes_count    INTEGER     NOT NULL DEFAULT 0,
  dislikes_count INTEGER     NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.community_posts;
CREATE POLICY "Enable read access for all users" ON public.community_posts
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for all users" ON public.community_posts;
CREATE POLICY "Enable insert for all users" ON public.community_posts
  FOR INSERT WITH CHECK (true);

-- ============================================================
-- 5. community_comments
-- ============================================================
CREATE TABLE IF NOT EXISTS public.community_comments (
  id             BIGINT      PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  post_id        BIGINT      NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
  author         TEXT        NOT NULL,
  author_user_id UUID        REFERENCES auth.users(id),
  content        TEXT        NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON public.community_comments;
CREATE POLICY "Allow public read access" ON public.community_comments
  FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert" ON public.community_comments;
CREATE POLICY "Allow authenticated users to insert" ON public.community_comments
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = author_user_id);

-- ============================================================
-- 6. community_reactions
-- ============================================================
CREATE TABLE IF NOT EXISTS public.community_reactions (
  id            UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id       BIGINT  NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
  user_id       UUID    NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reaction_type TEXT    NOT NULL CHECK (reaction_type IN ('like', 'dislike')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(post_id, user_id)
);

ALTER TABLE public.community_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON public.community_reactions;
CREATE POLICY "Allow public read access" ON public.community_reactions
  FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert reactions" ON public.community_reactions;
CREATE POLICY "Allow authenticated users to insert reactions" ON public.community_reactions
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users to delete their own reactions" ON public.community_reactions;
CREATE POLICY "Allow users to delete their own reactions" ON public.community_reactions
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users to update their own reactions" ON public.community_reactions;
CREATE POLICY "Allow users to update their own reactions" ON public.community_reactions
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- 7. partners
-- ============================================================
CREATE TABLE IF NOT EXISTS public.partners (
  id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name      TEXT        NOT NULL,
  business_type     TEXT        NOT NULL,
  contact_name      TEXT        NOT NULL,
  email             TEXT        NOT NULL UNIQUE,
  phone             TEXT        NOT NULL,
  address           TEXT,
  website           TEXT,
  description       TEXT,
  status            TEXT        NOT NULL DEFAULT 'pending',
  reject_reason     TEXT,
  visibility_status BOOLEAN     NOT NULL DEFAULT false,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  reviewed_at       TIMESTAMPTZ
);

ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage partners" ON public.partners;
CREATE POLICY "Admins can manage partners" ON public.partners
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('admin', 'super_admin'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('admin', 'super_admin'))
  );

-- ============================================================
-- 8. beauty_booking_requests
-- ============================================================
CREATE TABLE IF NOT EXISTS public.beauty_booking_requests (
  id                           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  category                     TEXT        NOT NULL DEFAULT 'beauty' CHECK (category = 'beauty'),
  customer_user_id             UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  beauty_category              TEXT        NOT NULL,
  region                       TEXT        NOT NULL,
  store_id                     TEXT        NOT NULL,
  store_name                   TEXT        NOT NULL,
  booking_date                 DATE        NOT NULL,
  booking_time                 TEXT        NOT NULL,
  designer_id                  TEXT,
  designer_name                TEXT,
  primary_service_id           TEXT,
  primary_service_name         TEXT,
  add_on_ids                   TEXT[]      NOT NULL DEFAULT '{}',
  add_on_names                 TEXT[]      NOT NULL DEFAULT '{}',
  base_price                   INTEGER     NOT NULL DEFAULT 0,
  add_on_price                 INTEGER     NOT NULL DEFAULT 0,
  designer_surcharge           INTEGER     NOT NULL DEFAULT 0,
  total_price                  INTEGER     NOT NULL DEFAULT 0,
  customer_name                TEXT        NOT NULL,
  customer_phone               TEXT        NOT NULL,
  customer_request             TEXT        NOT NULL DEFAULT '',
  current_image_url            TEXT,
  style_image_url              TEXT,
  image_urls                   TEXT[],
  communication_language       TEXT        NOT NULL,
  communication_intent         TEXT        NOT NULL,
  korean_message               TEXT        NOT NULL,
  localized_message            TEXT        NOT NULL,
  agreements                   JSONB       NOT NULL DEFAULT '{}',
  created_from_flow            TEXT        NOT NULL DEFAULT 'beauty-explore',
  payload_json                 JSONB       NOT NULL,
  status                       TEXT        NOT NULL DEFAULT 'requested'
    CHECK (status IN ('requested', 'confirmed', 'completed', 'canceled', 'failed', 'change_requested')),
  canceled_at                  TIMESTAMPTZ,
  canceled_by                  TEXT        CHECK (canceled_by IN ('customer', 'admin') OR canceled_by IS NULL),
  cancel_reason                TEXT        NOT NULL DEFAULT '',
  change_requested_at          TIMESTAMPTZ,
  change_reason                TEXT        NOT NULL DEFAULT '',
  status_before_change_request TEXT,
  change_request_status        TEXT        DEFAULT 'pending'
    CHECK (change_request_status IN ('approved', 'rejected', 'pending')),
  change_reviewed_at           TIMESTAMPTZ,
  change_reviewed_by           UUID        REFERENCES auth.users(id),
  change_review_note           TEXT        NOT NULL DEFAULT '',
  operator_status              TEXT        DEFAULT 'pending_assignment',
  internal_note                TEXT,
  shop_contacted               BOOLEAN     DEFAULT false,
  customer_contacted           BOOLEAN     DEFAULT false,
  follow_up_needed             BOOLEAN     DEFAULT false,
  alternative_offer_status     TEXT        DEFAULT 'none',
  alternative_offer_items      JSONB       DEFAULT '[]',
  alternative_offer_note       TEXT,
  alternative_offered_at       TIMESTAMPTZ,
  alternative_offered_by       UUID        REFERENCES auth.users(id),
  alternative_response_at      TIMESTAMPTZ,
  created_at                   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  updated_at                   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_beauty_booking_requests_created_at
  ON public.beauty_booking_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_beauty_booking_requests_booking_slot
  ON public.beauty_booking_requests(beauty_category, booking_date, booking_time);
CREATE INDEX IF NOT EXISTS idx_beauty_booking_requests_customer_user
  ON public.beauty_booking_requests(customer_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS beauty_booking_requests_operator_status_idx
  ON public.beauty_booking_requests(operator_status);
CREATE INDEX IF NOT EXISTS idx_beauty_booking_alternative_status
  ON public.beauty_booking_requests(alternative_offer_status);

ALTER TABLE public.beauty_booking_requests ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 9. beauty_booking_request_images
-- ============================================================
CREATE TABLE IF NOT EXISTS public.beauty_booking_request_images (
  id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id         UUID        NOT NULL REFERENCES public.beauty_booking_requests(id) ON DELETE CASCADE,
  user_id            UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  image_type         TEXT        NOT NULL CHECK (image_type IN ('current', 'style')),
  bucket_name        TEXT        NOT NULL DEFAULT 'booking',
  storage_path       TEXT        NOT NULL,
  original_file_name TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_beauty_images_request_id ON public.beauty_booking_request_images(request_id);
CREATE INDEX IF NOT EXISTS idx_beauty_images_user_id ON public.beauty_booking_request_images(user_id);

ALTER TABLE public.beauty_booking_request_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own booking images" ON public.beauty_booking_request_images;
CREATE POLICY "Users can view their own booking images"
  ON public.beauty_booking_request_images FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own booking images" ON public.beauty_booking_request_images;
CREATE POLICY "Users can insert their own booking images"
  ON public.beauty_booking_request_images FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can view all booking images" ON public.beauty_booking_request_images;
CREATE POLICY "Admins can view all booking images"
  ON public.beauty_booking_request_images FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('admin', 'super_admin'))
  );

-- ============================================================
-- 10. beauty_booking_notifications
-- ============================================================
CREATE TABLE IF NOT EXISTS public.beauty_booking_notifications (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  booking_id      UUID        NOT NULL REFERENCES public.beauty_booking_requests(id) ON DELETE CASCADE,
  event_type      TEXT        NOT NULL,
  title           TEXT        NOT NULL,
  message         TEXT        NOT NULL,
  channel         TEXT        NOT NULL DEFAULT 'in_app',
  status          TEXT        NOT NULL DEFAULT 'sent',
  metadata_json   JSONB       DEFAULT '{}',
  read_at         TIMESTAMPTZ,
  dispatch_status TEXT        DEFAULT 'pending',
  error_log       TEXT,
  dispatched_at   TIMESTAMPTZ,
  resend_count    INTEGER     DEFAULT 0,
  last_resent_at  TIMESTAMPTZ,
  resent_by       UUID
);

CREATE INDEX IF NOT EXISTS beauty_booking_notifications_user_id_idx
  ON public.beauty_booking_notifications(user_id);
CREATE INDEX IF NOT EXISTS beauty_booking_notifications_booking_id_idx
  ON public.beauty_booking_notifications(booking_id);
CREATE INDEX IF NOT EXISTS idx_beauty_booking_notifications_status
  ON public.beauty_booking_notifications(dispatch_status);
CREATE INDEX IF NOT EXISTS idx_beauty_booking_notifications_last_resent
  ON public.beauty_booking_notifications(last_resent_at);

ALTER TABLE public.beauty_booking_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own notifications" ON public.beauty_booking_notifications;
CREATE POLICY "Users can view their own notifications"
  ON public.beauty_booking_notifications FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "System can insert notifications" ON public.beauty_booking_notifications;
CREATE POLICY "System can insert notifications"
  ON public.beauty_booking_notifications FOR INSERT
  WITH CHECK (true);

-- ============================================================
-- 11. beauty_notification_preferences
-- ============================================================
CREATE TABLE IF NOT EXISTS public.beauty_notification_preferences (
  user_id                           UUID    PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  in_app_enabled                    BOOLEAN NOT NULL DEFAULT true,
  email_enabled                     BOOLEAN NOT NULL DEFAULT true,
  booking_updates_enabled           BOOLEAN NOT NULL DEFAULT true,
  change_request_updates_enabled    BOOLEAN NOT NULL DEFAULT true,
  alternative_offer_updates_enabled BOOLEAN NOT NULL DEFAULT true,
  updated_at                        TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

ALTER TABLE public.beauty_notification_preferences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own preferences" ON public.beauty_notification_preferences;
CREATE POLICY "Users can view their own preferences"
  ON public.beauty_notification_preferences FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own preferences" ON public.beauty_notification_preferences;
CREATE POLICY "Users can insert their own preferences"
  ON public.beauty_notification_preferences FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own preferences" ON public.beauty_notification_preferences;
CREATE POLICY "Users can update their own preferences"
  ON public.beauty_notification_preferences FOR UPDATE
  USING (auth.uid() = user_id);

-- ============================================================
-- 12. translation_contents
-- ============================================================
CREATE TABLE IF NOT EXISTS public.translation_contents (
  id             UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  domain         TEXT    NOT NULL CHECK (domain IN ('beauty', 'restaurant')),
  content_type   TEXT    NOT NULL CHECK (content_type IN ('shop', 'service', 'description', 'policy', 'chat_message', 'request_note', 'reservation')),
  source_table   TEXT    NOT NULL DEFAULT '',
  source_id      TEXT    NOT NULL DEFAULT '',
  source_locale  TEXT    NOT NULL DEFAULT 'ko',
  source_version INTEGER NOT NULL DEFAULT 1,
  schema_version TEXT    NOT NULL DEFAULT 'beauty-v1',
  mode           TEXT    NOT NULL CHECK (mode IN ('static', 'realtime', 'structured')),
  source_hash    TEXT    NOT NULL,
  source_payload JSONB,
  source_fields  JSONB   NOT NULL DEFAULT '[]',
  target_locales TEXT[]  NOT NULL DEFAULT '{}',
  status         TEXT    NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'translated', 'failed')),
  error_message  TEXT,
  metadata       JSONB   NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  UNIQUE(domain, content_type, source_table, source_id, source_hash)
);

CREATE INDEX IF NOT EXISTS idx_translation_contents_status
  ON public.translation_contents(status, domain, content_type);

ALTER TABLE public.translation_contents ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 13. translation_versions
-- ============================================================
CREATE TABLE IF NOT EXISTS public.translation_versions (
  id                 UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  content_id         UUID    NOT NULL REFERENCES public.translation_contents(id) ON DELETE CASCADE,
  target_locale      TEXT    NOT NULL CHECK (target_locale IN ('en', 'ja', 'zh-CN')),
  version            INTEGER NOT NULL DEFAULT 1,
  cache_key          TEXT    NOT NULL UNIQUE,
  source_hash        TEXT    NOT NULL,
  translation_engine TEXT    NOT NULL,
  glossary_version   INTEGER NOT NULL DEFAULT 1,
  translated_text    TEXT,
  translated_payload JSONB,
  translated_fields  JSONB   NOT NULL DEFAULT '[]',
  fallback_used      BOOLEAN NOT NULL DEFAULT false,
  status             TEXT    NOT NULL DEFAULT 'translated' CHECK (status IN ('pending', 'translated', 'failed')),
  error_message      TEXT,
  metadata           JSONB   NOT NULL DEFAULT '{}',
  created_at         TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  UNIQUE(content_id, target_locale, version)
);

CREATE INDEX IF NOT EXISTS idx_translation_versions_lookup
  ON public.translation_versions(content_id, target_locale, source_hash, version DESC);

ALTER TABLE public.translation_versions ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 14. translation_glossary
-- ============================================================
CREATE TABLE IF NOT EXISTS public.translation_glossary (
  id            UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  domain        TEXT    NOT NULL CHECK (domain IN ('beauty', 'restaurant')),
  source_locale TEXT    NOT NULL DEFAULT 'ko',
  target_locale TEXT    NOT NULL CHECK (target_locale IN ('en', 'ja', 'zh-CN')),
  source_term   TEXT    NOT NULL,
  target_term   TEXT    NOT NULL,
  priority      INTEGER NOT NULL DEFAULT 100,
  version       INTEGER NOT NULL DEFAULT 1,
  notes         TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  updated_by    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  UNIQUE(domain, source_locale, target_locale, source_term, version)
);

CREATE INDEX IF NOT EXISTS idx_translation_glossary_lookup
  ON public.translation_glossary(domain, target_locale, is_active, priority);

ALTER TABLE public.translation_glossary ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "translation_glossary_select_admin" ON public.translation_glossary;
CREATE POLICY "translation_glossary_select_admin" ON public.translation_glossary
  FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true));

DROP POLICY IF EXISTS "translation_glossary_write_admin" ON public.translation_glossary;
CREATE POLICY "translation_glossary_write_admin" ON public.translation_glossary
  FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_admin = true));

-- ============================================================
-- 15. translation_batch_jobs
-- ============================================================
CREATE TABLE IF NOT EXISTS public.translation_batch_jobs (
  id                UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  domain            TEXT    NOT NULL CHECK (domain IN ('beauty', 'restaurant')),
  content_type      TEXT    NOT NULL DEFAULT 'all',
  requested_locales TEXT[]  NOT NULL DEFAULT '{}',
  status            TEXT    NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'completed', 'failed')),
  queued_count      INTEGER NOT NULL DEFAULT 0,
  processed_count   INTEGER NOT NULL DEFAULT 0,
  translated_count  INTEGER NOT NULL DEFAULT 0,
  failed_count      INTEGER NOT NULL DEFAULT 0,
  summary           JSONB   NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  started_at        TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ
);

ALTER TABLE public.translation_batch_jobs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 16. booking_concierge_events
-- ============================================================
CREATE TABLE IF NOT EXISTS public.booking_concierge_events (
  id                 UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id         TEXT    NOT NULL,
  customer_locale    TEXT    NOT NULL,
  original_text      TEXT    NOT NULL,
  normalized_text    TEXT    NOT NULL,
  response_ko        TEXT    NOT NULL,
  response_localized TEXT    NOT NULL,
  structured_output  JSONB   NOT NULL,
  tools              JSONB   NOT NULL DEFAULT '[]',
  booking_id         TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_booking_concierge_session
  ON public.booking_concierge_events(session_id, created_at DESC);

ALTER TABLE public.booking_concierge_events ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 17. booking_records
-- ============================================================
CREATE TABLE IF NOT EXISTS public.booking_records (
  id           TEXT  PRIMARY KEY,
  session_id   TEXT  NOT NULL,
  service_name TEXT  NOT NULL,
  booking_date DATE  NOT NULL,
  booking_time TEXT  NOT NULL,
  status       TEXT  NOT NULL CHECK (status IN ('confirmed', 'cancelled')),
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW()),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_booking_records_session
  ON public.booking_records(session_id, created_at DESC);

ALTER TABLE public.booking_records ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 18. interpreter_sessions
-- ============================================================
CREATE TABLE IF NOT EXISTS public.interpreter_sessions (
  id              UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
  ephemeral_token TEXT  NOT NULL,
  customer_locale TEXT  NOT NULL,
  staff_locale    TEXT  NOT NULL,
  expires_at      TIMESTAMPTZ NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_interpreter_sessions_expiry
  ON public.interpreter_sessions(expires_at DESC);

ALTER TABLE public.interpreter_sessions ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 19. interpreter_turns
-- ============================================================
CREATE TABLE IF NOT EXISTS public.interpreter_turns (
  id              UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      UUID  NOT NULL REFERENCES public.interpreter_sessions(id) ON DELETE CASCADE,
  speaker         TEXT  NOT NULL CHECK (speaker IN ('customer', 'staff')),
  source_locale   TEXT  NOT NULL,
  target_locale   TEXT  NOT NULL,
  input_mode      TEXT  NOT NULL CHECK (input_mode IN ('voice', 'text')),
  original_text   TEXT  NOT NULL,
  translated_text TEXT  NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_interpreter_turns_session
  ON public.interpreter_turns(session_id, created_at DESC);

ALTER TABLE public.interpreter_turns ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 20. visitor_logs
-- ============================================================
CREATE TABLE IF NOT EXISTS public.visitor_logs (
  id         UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
  visitor_id TEXT  NOT NULL,
  visit_date DATE  NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_visitor_per_day
  ON public.visitor_logs(visitor_id, visit_date);

ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous visit tracking" ON public.visitor_logs;
CREATE POLICY "Allow anonymous visit tracking" ON public.visitor_logs
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admins to read visitor logs" ON public.visitor_logs;
CREATE POLICY "Allow admins to read visitor logs" ON public.visitor_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND (profiles.role = 'admin' OR profiles.role = 'super_admin')
    )
  );

-- ============================================================
-- 21. coupons
-- ============================================================
CREATE TABLE IF NOT EXISTS public.coupons (
  id             UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id        UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  discount_type  VARCHAR(20) NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
  discount_value INTEGER     NOT NULL DEFAULT 5,
  issue_reason   VARCHAR(50) NOT NULL CHECK (issue_reason IN ('signup', 'referred', 'referrer')),
  is_used        BOOLEAN     NOT NULL DEFAULT false,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_coupons_user_id ON public.coupons(user_id);
CREATE INDEX IF NOT EXISTS idx_coupons_is_used  ON public.coupons(is_used);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "coupons_select_own" ON public.coupons;
CREATE POLICY "coupons_select_own" ON public.coupons
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "coupons_insert_service_role" ON public.coupons;
CREATE POLICY "coupons_insert_service_role" ON public.coupons
  FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- 22. referrals
-- ============================================================
CREATE TABLE IF NOT EXISTS public.referrals (
  id          UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  referrer_id UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  referred_id UUID        NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_referrals_referrer_id  ON public.referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_profiles_referral_code ON public.profiles(referral_code);

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "referrals_select_participants" ON public.referrals;
CREATE POLICY "referrals_select_participants" ON public.referrals
  FOR SELECT USING (auth.uid() = referrer_id OR auth.uid() = referred_id);

DROP POLICY IF EXISTS "referrals_insert_service_role" ON public.referrals;
CREATE POLICY "referrals_insert_service_role" ON public.referrals
  FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- ============================================================
-- 23. Functions & Triggers
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_reaction_stats()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF NEW.reaction_type = 'like' THEN
      UPDATE public.community_posts SET likes_count = likes_count + 1 WHERE id = NEW.post_id;
    ELSE
      UPDATE public.community_posts SET dislikes_count = dislikes_count + 1 WHERE id = NEW.post_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF OLD.reaction_type = 'like' THEN
      UPDATE public.community_posts SET likes_count = GREATEST(0, likes_count - 1) WHERE id = OLD.post_id;
    ELSE
      UPDATE public.community_posts SET dislikes_count = GREATEST(0, dislikes_count - 1) WHERE id = OLD.post_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF OLD.reaction_type = 'like' AND NEW.reaction_type = 'dislike' THEN
      UPDATE public.community_posts SET likes_count = GREATEST(0, likes_count - 1), dislikes_count = dislikes_count + 1 WHERE id = NEW.post_id;
    ELSIF OLD.reaction_type = 'dislike' AND NEW.reaction_type = 'like' THEN
      UPDATE public.community_posts SET dislikes_count = GREATEST(0, dislikes_count - 1), likes_count = likes_count + 1 WHERE id = NEW.post_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_reaction_change ON public.community_reactions;
CREATE TRIGGER on_reaction_change
  AFTER INSERT OR DELETE OR UPDATE ON public.community_reactions
  FOR EACH ROW EXECUTE FUNCTION public.handle_reaction_stats();

CREATE OR REPLACE FUNCTION public.handle_comment_stats()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.community_posts SET comments = comments + 1 WHERE id = NEW.post_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.community_posts SET comments = GREATEST(0, comments - 1) WHERE id = OLD.post_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_comment_change ON public.community_comments;
CREATE TRIGGER on_comment_change
  AFTER INSERT OR DELETE ON public.community_comments
  FOR EACH ROW EXECUTE FUNCTION public.handle_comment_stats();

CREATE OR REPLACE FUNCTION public.generate_referral_code()
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
  chars  TEXT    := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code   TEXT    := '';
  length INTEGER;
  i      INTEGER;
BEGIN
  length := 6 + floor(random() * 3)::INTEGER;
  FOR i IN 1..length LOOP
    code := code || substr(chars, floor(random() * length(chars))::INTEGER + 1, 1);
  END LOOP;
  RETURN code;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_referral_code_on_profile_insert()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  new_code TEXT;
  attempts INTEGER := 0;
BEGIN
  LOOP
    new_code := public.generate_referral_code();
    IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE referral_code = new_code) THEN
      NEW.referral_code := new_code;
      RETURN NEW;
    END IF;
    attempts := attempts + 1;
    IF attempts >= 10 THEN
      RAISE EXCEPTION 'Failed to generate a unique referral_code after 10 attempts';
    END IF;
  END LOOP;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_referral_code ON public.profiles;
CREATE TRIGGER trg_set_referral_code
  BEFORE INSERT ON public.profiles
  FOR EACH ROW
  WHEN (NEW.referral_code IS NULL)
  EXECUTE FUNCTION public.set_referral_code_on_profile_insert();

CREATE OR REPLACE FUNCTION public.get_visitor_counts()
RETURNS TABLE (today_count BIGINT, total_count BIGINT)
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN QUERY
  SELECT
    (SELECT COUNT(*) FROM public.visitor_logs WHERE visit_date = CURRENT_DATE) AS today_count,
    (SELECT COUNT(DISTINCT visitor_id) FROM public.visitor_logs) AS total_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_referral_code(p_referrer_code TEXT, p_referred_id UUID)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_referrer_id UUID;
BEGIN
  SELECT id INTO v_referrer_id FROM public.profiles WHERE referral_code = p_referrer_code LIMIT 1;
  IF v_referrer_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'invalid_code');
  END IF;
  IF v_referrer_id = p_referred_id THEN
    RETURN json_build_object('success', false, 'error', 'self_referral');
  END IF;
  IF EXISTS (SELECT 1 FROM public.referrals WHERE referred_id = p_referred_id) THEN
    RETURN json_build_object('success', false, 'error', 'already_referred');
  END IF;
  INSERT INTO public.referrals (referrer_id, referred_id) VALUES (v_referrer_id, p_referred_id);
  INSERT INTO public.coupons (user_id, discount_type, discount_value, issue_reason) VALUES (v_referrer_id, 'percent', 5, 'referrer');
  INSERT INTO public.coupons (user_id, discount_type, discount_value, issue_reason) VALUES (p_referred_id, 'percent', 5, 'referred');
  RETURN json_build_object('success', true, 'error', null);
EXCEPTION WHEN OTHERS THEN
  RETURN json_build_object('success', false, 'error', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION public.apply_referral_code(TEXT, UUID) TO authenticated;

CREATE OR REPLACE FUNCTION public.issue_signup_coupon(p_user_id UUID)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.coupons WHERE user_id = p_user_id AND issue_reason = 'signup') THEN
    RETURN json_build_object('success', false, 'error', 'already_issued');
  END IF;
  INSERT INTO public.coupons (user_id, discount_type, discount_value, issue_reason, is_used)
  VALUES (p_user_id, 'percent', 5, 'signup', false);
  RETURN json_build_object('success', true, 'error', null);
EXCEPTION WHEN OTHERS THEN
  RETURN json_build_object('success', false, 'error', SQLERRM);
END;
$$;

GRANT EXECUTE ON FUNCTION public.issue_signup_coupon(UUID) TO authenticated, anon;

-- ============================================================
-- 24. Storage Buckets
-- ============================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

INSERT INTO storage.buckets (id, name, public)
VALUES ('booking', 'booking', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('community', 'community', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('partner_documents', 'partner_documents', false)
ON CONFLICT (id) DO NOTHING;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Public can read avatars') THEN
    CREATE POLICY "Public can read avatars" ON storage.objects FOR SELECT TO public USING (bucket_id = 'avatars');
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Authenticated users can upload avatars') THEN
    CREATE POLICY "Authenticated users can upload avatars" ON storage.objects FOR INSERT TO authenticated
      WITH CHECK (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Users can upload booking images') THEN
    CREATE POLICY "Users can upload booking images" ON storage.objects FOR INSERT TO authenticated
      WITH CHECK (bucket_id = 'booking');
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Users can read own booking images') THEN
    CREATE POLICY "Users can read own booking images" ON storage.objects FOR SELECT TO authenticated
      USING (bucket_id = 'booking');
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Public can read community images') THEN
    CREATE POLICY "Public can read community images" ON storage.objects FOR SELECT TO public USING (bucket_id = 'community');
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Authenticated users can upload community images') THEN
    CREATE POLICY "Authenticated users can upload community images" ON storage.objects FOR INSERT TO authenticated
      WITH CHECK (bucket_id = 'community');
  END IF;
END $$;
