CREATE TABLE IF NOT EXISTS public.community_posts (
  id bigint generated by default as identity primary key,
  author text NOT NULL,
  flag text NOT NULL,
  type text NOT NULL, -- 'meetup', 'help', 'travel'
  title text NOT NULL,
  "desc" text NOT NULL,
  time text NOT NULL,
  comments int DEFAULT 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Row Level Security (RLS) but allow anonymous access for demo flexibility
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.community_posts
  FOR SELECT
  USING (true);

CREATE POLICY "Enable insert for all users" ON public.community_posts
  FOR INSERT
  WITH CHECK (true);
