-- ============================================================
-- K-Trip 협력업체 (Partners) 테이블
-- Supabase Dashboard → SQL Editor 에서 실행하세요
-- ============================================================

CREATE TABLE IF NOT EXISTS public.partners (
  id              bigint generated by default as identity primary key,
  company_name    text NOT NULL,                       -- 업체명
  business_type   text NOT NULL,                       -- 업종
  contact_name    text NOT NULL,                       -- 담당자명
  email           text NOT NULL UNIQUE,                -- 이메일
  phone           text NOT NULL,                       -- 연락처
  address         text,                                -- 주소 (선택)
  website         text,                                -- 웹사이트 (선택)
  description     text,                                -- 업체 소개 (선택)
  status          text NOT NULL DEFAULT 'pending',     -- pending / approved / rejected
  reject_reason   text,                                -- 거절 사유 (선택)
  created_at      timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  reviewed_at     timestamp with time zone             -- 관리자 처리 일시
);

-- RLS 활성화
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;

-- 누구나 신청(INSERT) 가능
CREATE POLICY "partners_insert_all" ON public.partners
  FOR INSERT WITH CHECK (true);

-- 누구나 조회(SELECT) 가능
CREATE POLICY "partners_select_all" ON public.partners
  FOR SELECT USING (true);

-- 누구나 상태 업데이트(UPDATE) 가능 — 관리자 구분은 앱 레벨에서 처리
CREATE POLICY "partners_update_all" ON public.partners
  FOR UPDATE USING (true);

-- ============================================================
-- profiles 테이블에 is_admin 컬럼 추가 (이미 있으면 무시됨)
-- ============================================================
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;

-- 관리자 계정 지정 (실제 관리자 이메일로 변경하세요)
-- UPDATE public.profiles SET is_admin = true WHERE email = 'admin@example.com';
