const fs = require('fs');

const translations = {
  "ar": {
    "privacy_policy": { "title": "سياسة الخصوصية", "effective_date": "تاريخ النفاذ: 21 أبريل 2024", "table": { "category": "الفئة", "items": "العناصر التي تم جمعها", "purpose": "الغرض", "retention": "فترة الاحتفاظ" }, "collection": { "title": "1. جمع واستخدام المعلومات الشخصية", "required": "مطلوب", "required_items": "الاسم، البريد الإلكتروني، معلومات الحجز (التاريخ، الوقت، المتجر، الخدمة)، معرف تسجيل دخول اجتماعي", "required_purpose": "تسجيل المستخدم، التعريف، توفير الخدمة (الحجز)، استشارة العملاء", "auto": "الجمع التلقائي", "auto_items": "عنوان IP، ملفات تعريف الارتباط، معلومات الجهاز، سجلات استخدام الخدمة", "auto_purpose": "تحسين جودة الخدمة ومنع الاحتيال" }, "retention": { "title": "2. فترة الاحتفاظ والاستخدام", "content": "من حيث المبدأ، يتم الاحتفاظ بالمعلومات الشخصية حتى يتم سحب العضوية. ومع ذلك، قد يتم الاحتفاظ بها لفترة تتطلبها القوانين ذات الصلة إذا لزم الأمر.", "legal_basis": "الامتثال للقوانين ذات الصلة (على سبيل المثال، قانون التجارة الإلكترونية)" }, "third_party": { "title": "3. تقديم المعلومات الشخصية لأطراف ثالثة", "content": "تقوم MyKello بتزويد الشركاء التاليين بالمعلومات الشخصية لتسهيل تقديم الخدمة.", "providers": "Supabase (قاعدة البيانات)، Google (المصادقة)، X (المصادقة)" }, "overseas": { "title": "4. نقل المعلومات الشخصية إلى الخارج", "recipient": "المستلم", "country": "البلد", "purpose": "الغرض من النقل", "items": "العناصر المنقولة", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "الولايات المتحدة الأمريكية", "storage_auth": "تخزين البيانات ومصادقة المستخدم (OAuth 2.0)", "log_items": "البريد الإلكتروني، معلومات الملف الشخصي، سجلات استخدام الخدمة" }, "destruction": { "title": "5. إجراءات وطريقة الإتلاف", "content": "يتم إتلاف المعلومات الشخصية فور تحقيق الغرض منها. يتم حذف الملفات الإلكترونية باستخدام طرق تقنية تجعل استعادتها مستحيلة." } },
    "signup_consent": { "all_agree": "أوافق على جميع الشروط.", "privacy_required": "[إلزامي] الموافقة على جمع واستخدام المعلومات الشخصية", "privacy_optional": "[اختياري] الموافقة على تلقي معلومات التسويق", "view_detail": "عرض التفاصيل", "terms_required": "[إلزامي] الموافقة على شروط الخدمة" },
    "terms_of_service": { "title": "شروط الخدمة", "effective_date": "تاريخ النفاذ: 21 أبريل 2024", "definitions": { "title": "1. تعريف الخدمة", "content": "توفر MyKello منصة وكالة حجز خدمات التجميل لتسهيل الحجوزات والتواصل بين المستخدمين ومقدمي خدمات التجميل." }, "benefits": { "title": "2. فوائد العضو", "signup": "يحصل الأعضاء الجدد على كوبون خصم 5% عند التسجيل بنجاح.", "referral": "عندما ينضم عضو جديد باستخدام كود إحالة، يحصل كل من المحيل والمحال على كوبون خصم 5%." }, "refund_policy": { "title": "3. سياسة الإلغاء والاسترداد", "subtitle": "يتم احتساب معدلات الاسترداد بناءً على وقت الإلغاء قبل الموعد المقرر:", "five_days": "قبل 5 أيام: استرداد 100%", "three_days": "قبل 3 أيام: استرداد 90%", "two_days": "قبل يومين: استرداد 70%", "one_day": "قبل يوم واحد: استرداد 50%", "same_day": "في نفس اليوم أو عدم الحضور: لا استرداد", "note": "قد تختلف معالجة الاسترداد النهائي اعتمادًا على سياسة المتجر المحددة." }, "liability": { "title": "4. حدود المسؤولية", "interpretation": "ميزة 'الترجمة الفورية' هي أداة تكميلية مقدمة لراحة المستخدم. MyKello ليست مسؤولة عن أخطاء الحجز أو النزاعات الناشئة عن عدم الدقة في ترجمة الذكاء الاصطناعي أو الترجمة اليدوية.", "community": "MyKello ليست مسؤولة عن أي أضرار أو حوادث أو نزاعات ناتجة عن اللقاءات التطوعية غير المتصلة بالإنترنت أو المعاملات الشخصية بين المستخدمين التي تتم من خلال ميزات المجتمع." } }
  },
  "en": {
    "privacy_policy": { "title": "Privacy Policy", "effective_date": "Effective Date: April 21, 2024", "table": { "category": "Category", "items": "Collected Items", "purpose": "Purpose", "retention": "Retention Period" }, "collection": { "title": "1. Collection and Use of Personal Information", "required": "Required", "required_items": "Name, Email, Reservation Info (Date, Time, Shop, Service), Social Login ID", "required_purpose": "User Registration, Identification, Service Provision (Booking), Customer Consultation", "auto": "Automatic Collection", "auto_items": "IP Address, Cookies, Device Info, Service Usage Logs", "auto_purpose": "Improving Service Quality and Preventing Fraud" }, "retention": { "title": "2. Retention and Use Period", "content": "In principle, personal information is retained until membership withdrawal. However, it may be kept for a period required by relevant laws if necessary.", "legal_basis": "Compliance with relevant laws (e.g., E-commerce Act)" }, "third_party": { "title": "3. Providing Personal Information to Third Parties", "content": "MyKello provides personal information to the following partners to facilitate service delivery.", "providers": "Supabase (Database), Google (Authentication), X (Authentication)" }, "overseas": { "title": "4. Overseas Transfer of Personal Information", "recipient": "Recipient", "country": "Country", "purpose": "Transfer Purpose", "items": "Transferred Items", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "USA", "storage_auth": "Data Storage and User Authentication (OAuth 2.0)", "log_items": "Email, Profile Info, Service Usage Logs" }, "destruction": { "title": "5. Destruction Procedure and Method", "content": "Personal information is destroyed immediately after the purpose is achieved. Electronic files are deleted using technical methods that make recovery impossible." } },
    "signup_consent": { "all_agree": "I agree to all terms.", "privacy_required": "[Required] Consent to Collection and Use of Personal Information", "privacy_optional": "[Optional] Consent to Marketing Information", "view_detail": "View Detail", "terms_required": "[Required] Consent to Terms of Service" },
    "terms_of_service": { "title": "Terms of Service", "effective_date": "Effective Date: April 21, 2024", "definitions": { "title": "1. Definition of Service", "content": "MyKello provides a beauty service reservation agency platform to facilitate bookings and communication between users and beauty service providers." }, "benefits": { "title": "2. Member Benefits", "signup": "New members receive a 5% discount coupon upon successful signup.", "referral": "When a new member joins using a referral code, both the referrer and referee receive a 5% discount coupon." }, "refund_policy": { "title": "3. Cancellation & Refund Policy", "subtitle": "Refund rates are calculated based on the cancellation time before the scheduled appointment:", "five_days": "5 days prior: 100% Refund", "three_days": "3 days prior: 90% Refund", "two_days": "2 days prior: 70% Refund", "one_day": "1 day prior: 50% Refund", "same_day": "Same-day or No-show: No Refund", "note": "Final refund processing may vary depending on the specific store's policy." }, "liability": { "title": "4. Limitation of Liability", "interpretation": "The 'Real-time Interpretation' feature is a supplementary tool provided for user convenience. MyKello is not liable for reservation errors or disputes arising from inaccuracies in AI translation or manual interpretation.", "community": "MyKello is not responsible for any damages, incidents, or disputes resulting from voluntary offline meetups or personal transactions between users conducted through the community features." } }
  },
  "ja": {
    "privacy_policy": { "title": "プライバシーポリシー", "effective_date": "施行日：2024年4月21日", "table": { "category": "項目", "items": "収集情報", "purpose": "収集目的", "retention": "保有期間" }, "collection": { "title": "1. 個人情報の収集および利用", "required": "必須", "required_items": "氏名、メールアドレス、予約情報（日付、時間、店舗、サービス）、SNSログインID", "required_purpose": "会員登録、本人識別、サービス提供（予約）、カスタマー相談", "auto": "自動収集", "auto_items": "IPアドレス、クッキー、端末情報、サービス利用履歴", "auto_purpose": "サービス品質の向上および不正利用の防止" }, "retention": { "title": "2. 保有および利用期間", "content": "個人情報は原則として会員退会時まで保有します。ただし、関連法令により保存する必要がある場合は、当該期間中保管することがあります。", "legal_basis": "関連法令の遵守（例：電子商取引法など）" }, "third_party": { "title": "3. 個人情報の第三者提供", "content": "MyKelloはサービス提供のため、以下のパートナーに個人情報を提供します。", "providers": "Supabase（データベース）、Google（本人認証）、X（本人認証）" }, "overseas": { "title": "4. 個人情報の国外移転", "recipient": "受領者", "country": "国", "purpose": "移転目的", "items": "移転項目", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "アメリカ", "storage_auth": "データ保存およびユーザー認証（OAuth 2.0）", "log_items": "メールアドレス、プロフィール情報、サービス利用ログ" }, "destruction": { "title": "5. 破棄の手順および方法", "content": "個人情報は目的達成後、遅滞なく破棄します。電子的なファイル形式は、復元が不可能な技術的方法で削除します。" } },
    "signup_consent": { "all_agree": "すべての規約に同意します。", "privacy_required": "[必須] 個人情報の収集および利用への同意", "privacy_optional": "[選択] マーケティング情報の受信への同意", "view_detail": "詳細を見る", "terms_required": "[必須] サービス利用規約への同意" },
    "terms_of_service": { "title": "サービス利用規約", "effective_date": "施行日：2024年4月21日", "definitions": { "title": "1. サービスの定義", "content": "MyKelloは、ユーザーとビューティーサービス提供者の間の予約およびコミュニケーションを支援する、ビューティーサービス予約代行プラットフォームを提供します。" }, "benefits": { "title": "2. 会員特典", "signup": "新規登録時に5%割引クーポンが支給されます。", "referral": "招待コードを通じて登録した場合、招待した側と招待された側の両方に5%割引クーポンが支給されます。" }, "refund_policy": { "title": "3. キャンセルおよび返金規定", "subtitle": "予約日を基準としたキャンセル時点に応じて、以下の返金率が適用されます。", "five_days": "5日前：100%返金", "three_days": "3日前：90%返金", "two_days": "2日前：70%返金", "one_day": "1日前：50%返金", "same_day": "当日または無断キャンセル（No-show）：返金不可", "note": "最終的な返金処理は各店舗のポリシーにより異なる場合があります。" }, "liability": { "title": "4. 責任の制限", "interpretation": "「リアルタイム通訳」機能は、ユーザーの利便性のために提供される付加的なツールです。MyKelloは、AI翻訳または手動通訳の不一致によって発生する予約エラーや紛争について責任を負いません。", "community": "ユーザーがコミュニティ機能を通じて自発的に行ったオフラインの集まりや個人間の取引から発生する損害、事故、または紛争について、MyKelloは責任を負いません。" } }
  },
  "ko": {
    "privacy_policy": { "title": "개인정보 처리방침", "effective_date": "시행일: 2024년 4월 21일", "table": { "category": "항목", "items": "수집 정보", "purpose": "수집 목적", "retention": "보유 기간" }, "collection": { "title": "1. 개인정보의 수집 및 이용", "required": "필수", "required_items": "이름, 이메일, 예약 정보(날짜, 시간, 매장, 서비스), 소셜 로그인 ID", "required_purpose": "회원 가입, 본인 식별, 서비스 제공(예약), 고객 상담", "auto": "자동 수집", "auto_items": "IP 주소, 쿠키, 기기 정보, 서비스 이용 기록", "auto_purpose": "서비스 품질 개선 및 부정 이용 방지" }, "retention": { "title": "2. 보유 및 이용 기간", "content": "개인정보는 원칙적으로 회원 탈퇴 시까지 보유합니다. 단, 관련 법령에 의해 보존할 필요가 있는 경우 해당 기간 동안 보관할 수 있습니다.", "legal_basis": "관련 법령 준수(예: 전자상거래법)" }, "third_party": { "title": "3. 개인정보의 제3자 제공", "content": "MyKello는 서비스 제공을 위해 아래의 파트너에게 개인정보를 제공합니다.", "providers": "Supabase (데이터베이스), Google (본인 인증), X (본인 인증)" }, "overseas": { "title": "4. 개인정보의 국외 이전", "recipient": "수신자", "country": "국가", "purpose": "이전 목적", "items": "이전 항목", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "미국", "storage_auth": "데이터 저장 및 사용자 인증(OAuth 2.0)", "log_items": "이메일, 프로필 정보, 서비스 이용 로그" }, "destruction": { "title": "5. 파기 절차 및 방법", "content": "개인정보는 목적 달성 후 지체 없이 파기합니다. 전자적 파일 형태는 복구가 불가능한 기술적 방법으로 삭제합니다." } },
    "signup_consent": { "all_agree": "모든 약관에 동의합니다.", "privacy_required": "[필수] 개인정보 수집 및 이용 동의", "privacy_optional": "[선택] 마케팅 정보 수신 동의", "view_detail": "보기", "terms_required": "[필수] 서비스 이용약관 동의" },
    "terms_of_service": { "title": "서비스 이용약관", "effective_date": "시행일: 2024년 4월 21일", "definitions": { "title": "1. 서비스의 정의", "content": "MyKello는 사용자와 뷰티 서비스 제공자 사이의 예약 및 소통을 돕는 뷰티 서비스 예약 대행 플랫폼을 제공합니다." }, "benefits": { "title": "2. 회원 혜택", "signup": "신규 가입 시 5% 할인 쿠폰이 지급됩니다.", "referral": "추천인 코드를 통해 가입 시, 추천인과 피추천인 모두에게 5% 할인 쿠폰이 지급됩니다." }, "refund_policy": { "title": "3. 취소 및 환불 규정", "subtitle": "예약일 기준 취소 시점에 따라 다음과 같이 환불 비율이 적용됩니다.", "five_days": "5일 전: 100% 환불", "three_days": "3일 전: 90% 환불", "two_days": "2일 전: 70% 환불", "one_day": "1일 전: 50% 환불", "same_day": "당일 또는 No-show: 환불 불가", "note": "최종 환불 처리는 매장별 정책에 따라 상이할 수 있습니다." }, "liability": { "title": "4. 책임의 한계", "interpretation": "실시간 통역 기능은 사용자 편의를 위해 제공되는 부가 도구입니다. MyKello는 AI 번역 또는 수동 통역의 불일치로 인해 발생하는 예약 오류나 분쟁에 대해 책임을 지지 않습니다.", "community": "사용자가 커뮤니티 기능을 통해 자발적으로 진행한 오프라인 모임이나 개인 간 거래에서 발생하는 손해, 사고 또는 분쟁에 대해 MyKello는 책임을 지지 않습니다." } }
  },
  "th": {
    "privacy_policy": { "title": "นโยบายความเป็นส่วนตัว", "effective_date": "วันที่เข้าผล: 21 เมษายน 2024", "table": { "category": "หมวดหมู่", "items": "ข้อมูลที่เก็บรวบรวม", "purpose": "วัตถุประสงค์ในการเก็บรวบรวม", "retention": "ระยะเวลาการเก็บรักษา" }, "collection": { "title": "1. การเก็บรวบรวมและการใช้ข้อมูลส่วนบุคคล", "required": "จำเป็น", "required_items": "ชื่อ-นามสกุล, อีเมล, ข้อมูลการจอง (วันที่, เวลา, ร้านค้า, บริการ), ไอดีเข้าสู่ระบบโซเชียล", "required_purpose": "ลงทะเบียนผู้ใช้, ยืนยันตัวตน, ให้บริการ (การจอง), ปรึกษาลูกค้า", "auto": "การเก็บรวบรวมอัตโนมัติ", "auto_items": "ที่อยู่ IP, คุกกี้, ข้อมูลจากอุปกรณ์, ประวัติการใช้บริการ", "auto_purpose": "การปรับปรุงคุณภาพบริการและการป้องกันการฉ้อโกง" }, "retention": { "title": "2. ระยะเวลาการเก็บรักษาและการใช้", "content": "ตามหลักการ ข้อมูลส่วนบุคคลจะถูกเก็บรักษาไว้จนกว่าจะถอนตัวจากการเป็นสมาชิก อย่างไรก็ตาม หากมีความจำเป็นตามกฎหมายที่เกี่ยวข้อง ข้อมูลอาจถูกเก็บรักษาไว้ตามระยะเวลาที่กฎหมายกำหนด", "legal_basis": "การปฏิบัติตามกฎหมายที่เกี่ยวข้อง (เช่น กฎหมายพาณิชย์อิเล็กทรอนิกส์ เป็นต้น)" }, "third_party": { "title": "3. การให้ข้อมูลส่วนบุคคลแก่บุคคลที่สาม", "content": "MyKello ให้ข้อมูลส่วนบุคคลแก่พันธมิตรดังต่อไปนี้เพื่ออำนวยความสะดวกในการจัดส่งบริการ", "providers": "Supabase (ฐานข้อมูล), Google (การยืนยันตัวตน), X (การยืนยันตัวตน)" }, "overseas": { "title": "4. การโอนข้อมูลส่วนบุคคลไปต่างประเทศ", "recipient": "ผู้รับ", "country": "ประเทศ", "purpose": "วัตถุประสงค์การโอน", "items": "ข้อมูลที่โอน", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "สหรัฐอเมริกา (USA)", "storage_auth": "การจัดเก็บข้อมูลและการยืนยันตัวตน OAuth 2.0", "log_items": "อีเมล, ข้อมูลโปรไฟล์, บันทึกการใช้บริการ" }, "destruction": { "title": "5. ขั้นตอนและวิธีการทำลายข้อมูล", "content": "ข้อมูลส่วนบุคคลจะถูกทำลายทันทีหลังจากบรรลุวัตถุประสงค์แล้ว ไฟล์อิเล็กทรอนิกส์จะถูกลบโดยใช้วิธีการทางเทคนิคที่ทำให้การกู้คืนเป็นไปไม่ได้" } },
    "signup_consent": { "all_agree": "ฉันยอมรับข้อกำหนดทั้งหมด", "privacy_required": "[จำเป็น] ยอมรับการเก็บรวบรวมและการใช้ข้อมูลส่วนบุคคล", "privacy_optional": "[ทางเลือก] ยอมรับการรับข้อมูลทางการตลาด", "view_detail": "ดูรายละเอียด", "terms_required": "[จำเป็น] ยอมรับเงื่อนไขการใช้บริการ" },
    "terms_of_service": { "title": "เงื่อนไขการใช้บริการ", "effective_date": "วันที่เข้าผล: 21 เมษายน 2024", "definitions": { "title": "1. คำนิยามของบริการ", "content": "MyKello ให้บริการแพลตฟอร์มตัวแทนรับจองบริการความงาม เพื่ออำนวยความสะดวกในการจองและการสื่อสารระหว่างผู้ใช้และผู้ให้บริการความงาม" }, "benefits": { "title": "2. สิทธิประโยชน์ของสมาชิก", "signup": "สมาชิกใหม่จะได้รับคูปองส่วนลด 5% เมื่อลงทะเบียนสำเร็จ", "referral": "เมื่อลงทะเบียนด้วยรหัสแนะนำ ทั้งผู้แนะนำและผู้สมัครใหม่จะได้รับคูปองส่วนลด 5%" }, "refund_policy": { "title": "3. นโนบายการยกเลิกและคืนเงิน", "subtitle": "อัตราการคืนเงินถูกคำนวณตามระยะเวลาการยกเลิกก่อนถึงวันจองดังนี้:", "five_days": "5 วันล่วงหน้า: คืนเงิน 100%", "three_days": "3 วันล่วงหน้า: คืนเงิน 90%", "two_days": "2 วันล่วงหน้า: คืนเงิน 70%", "one_day": "1 วันล่วงหน้า: คืนเงิน 50%", "same_day": "วันจองหรือกรณี No-show: ไม่มีการคืนเงิน", "note": "การคืนเงินขั้นสุดท้ายอาจแตกต่างกันไปตามนโยบายของแต่ละร้านค้า" }, "liability": { "title": "4. ข้อจำกัดความรับผิดชอบ", "interpretation": "ฟีเจอร์ 'การแปลภาษาแบบเรียลไทม์' เป็นเครื่องมือเสริมเพื่อความสะดวกของผู้ใช้ MyKello จะไม่รับผิดชอบต่อความล่าช้าหรือข้อผิดพลาดในการจองที่เกิดจากความไม่ถูกต้องของการแปล", "community": "MyKello จะไม่รับผิดชอบต่อความเสียหาย อุบัติเหตุ หรือข้อพิพาทใดๆ ที่เกิดจากการพบปะออฟไลน์หรือการทำธุรกรรมส่วนตัวระหว่างผู้ใช้ผ่านฟีเจอร์ชุมชน" } }
  },
  "vi": {
    "privacy_policy": { "title": "Chính sách Bảo mật", "effective_date": "Ngày có hiệu lực: 21 tháng 4, 2024", "table": { "category": "Danh mục", "items": "Thông tin thu thập", "purpose": "Mục đích", "retention": "Thời hạn lưu trữ" }, "collection": { "title": "1. Thu thập và Sử dụng Thông tin Cá nhân", "required": "Bắt buộc", "required_items": "Tên, Email, Thông tin đặt chỗ (Ngày, Giờ, Cửa hàng, Dịch vụ), ID đăng nhập mạng xã hội", "required_purpose": "Đăng ký người dùng, Xác thực, Cung cấp dịch vụ (Đặt chỗ), Tư vấn khách hàng", "auto": "Thu thập tự động", "auto_items": "Địa chỉ IP, Cookies, Thông tin thiết bị, Lịch sử sử dụng dịch vụ", "auto_purpose": "Cải thiện chất lượng dịch vụ và ngăn ngừa gian lận" }, "retention": { "title": "2. Thời hạn Lưu trữ và Sử dụng", "content": "Về nguyên tắc, thông tin cá nhân được giữ lại cho đến khi rút khỏi tư cách thành viên. Tuy nhiên, nó có thể được giữ trong một thời gian theo yêu cầu của pháp luật liên quan nếu cần thiết.", "legal_basis": "Tuân thủ các luật liên quan (ví dụ: Luật Thương mại Điện tử)" }, "third_party": { "title": "3. Cung cấp Thông tin Cá nhân cho Bên thứ ba", "content": "MyKello cung cấp thông tin cá nhân cho các đối tác sau để tạo điều kiện cung cấp dịch vụ.", "providers": "Supabase (Cơ sở dữ liệu), Google (Xác thực), X (Xác thực)" }, "overseas": { "title": "4. Chuyển Thông tin Cá nhân ra Nước ngoài", "recipient": "Người nhận", "country": "Quốc gia", "purpose": "Mục đích chuyển", "items": "Thông tin được chuyển", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "Hoa Kỳ", "storage_auth": "Lưu trữ dữ liệu và xác thực người dùng (OAuth 2.0)", "log_items": "Email, Thông tin hồ sơ, Nhật ký sử dụng dịch vụ" }, "destruction": { "title": "5. Quy trình và Phương pháp Tiêu hủy", "content": "Thông tin cá nhân được tiêu hủy ngay lập tức sau khi đạt được mục đích. Các tệp điện tử được xóa bằng các phương pháp kỹ thuật khiến việc khôi phục là không thể." } },
    "signup_consent": { "all_agree": "Tôi đồng ý với tất cả các điều khoản.", "privacy_required": "[Bắt buộc] Đồng ý Thu thập và Sử dụng Thông tin Cá nhân", "privacy_optional": "[Tùy chọn] Đồng ý Nhận Thông tin Tiếp thị", "view_detail": "Chi tiết", "terms_required": "[Bắt buộc] Đồng ý với Điều khoản Dịch vụ" },
    "terms_of_service": { "title": "Điều khoản Dịch vụ", "effective_date": "Ngày có hiệu lực: 21 tháng 4, 2024", "definitions": { "title": "1. Định nghĩa Dịch vụ", "content": "MyKello cung cấp một nền tảng đại lý đặt chỗ dịch vụ làm đẹp nhằm tạo điều kiện thuận lợi cho việc đặt chỗ và liên lạc giữa người dùng và các nhà cung cấp dịch vụ làm đẹp." }, "benefits": { "title": "2. Quyền lợi Thành viên", "signup": "Thành viên mới nhận được phiếu giảm giá 5% khi đăng ký thành công.", "referral": "Khi một thành viên mới tham gia bằng mã giới thiệu, cả người giới thiệu và người được giới thiệu đều nhận được phiếu giảm giá 5%." }, "refund_policy": { "title": "3. Chính sách Hủy bỏ & Hoàn tiền", "subtitle": "Số tiền hoàn lại được tính dựa trên thời gian hủy trước cuộc hẹn đã lên lịch:", "five_days": "5 ngày trước: Hoàn tiền 100%", "three_days": "3 ngày trước: Hoàn tiền 90%", "two_days": "2 ngày trước: Hoàn tiền 70%", "one_day": "1 ngày trước: Hoàn tiền 50%", "same_day": "Trong ngày hoặc Không đến: Không hoàn tiền", "note": "Quá trình hoàn tiền cuối cùng có thể thay đổi tùy thuộc vào chính sách của từng cửa hàng cụ thể." }, "liability": { "title": "4. Giới thiệu về Trách nhiệm pháp lý", "interpretation": "Tính năng 'Thông dịch viên thời gian thực' là một công cụ bổ sung được cung cấp để thuận tiện cho người dùng. MyKello không chịu trách nhiệm về các lỗi đặt chỗ hoặc tranh chấp phát sinh từ sự thiếu chính xác trong bản dịch AI hoặc thông dịch thủ công.", "community": "MyKello không chịu trách nhiệm cho bất kỳ thiệt hại, sự cố hoặc tranh chấp nào phát sinh từ các cuộc gặp gỡ ngoại tuyến tự nguyện hoặc các giao dịch cá nhân giữa những người dùng được thực hiện thông qua các tính năng cộng đồng." } }
  },
  "zh-CN": {
    "privacy_policy": { "title": "隐私政策", "effective_date": "生效日期：2024年4月21日", "table": { "category": "项目", "items": "收集信息", "purpose": "收集目的", "retention": "保存期限" }, "collection": { "title": "1. 个人信息的收集与使用", "required": "必选", "required_items": "姓名、电子邮箱、预约信息（日期、时间、店铺、服务）、社交账号登录ID", "required_purpose": "会员注册、身份识别、提供服务（预约）、客户咨询", "auto": "自动收集", "auto_items": "IP 地址、Cookie、设备信息、服务使用记录", "auto_purpose": "提高服务质量及防止异常使用" }, "retention": { "title": "2. 保存及使用期限", "content": "原则上，个人信息将保存至注销会员为止。但根据相关法令规定有必要保存时，可在该期限内予以保存。", "legal_basis": "遵守相关法令（如《电子商务法》等）" }, "third_party": { "title": "3. 向第三方提供个人信息", "content": "MyKello 为提供服务，向以下合作伙伴提供个人信息。", "providers": "Supabase（数据库）、Google（身份验证）、X（身份验证）" }, "overseas": { "title": "4. 个人信息跨境传输", "recipient": "接收方", "country": "国家", "purpose": "传输目的", "items": "传输项目", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "美国", "storage_auth": "数据存储及用户身份验证 (OAuth 2.0)", "log_items": "电子邮箱、个人资料信息、服务使用日志" }, "destruction": { "title": "5. 销毁程序及方法", "content": "个人信息在达到使用目的后将立即销毁。电子文件将通过无法还原的技术方法进行删除。" } },
    "signup_consent": { "all_agree": "我同意所有条款。", "privacy_required": "[必选] 同意收集并使用个人信息", "privacy_optional": "[可选] 同意接收营销信息", "view_detail": "查看详情", "terms_required": "[必选] 同意服务条款" },
    "terms_of_service": { "title": "服务条款", "effective_date": "生效日期：2024年4月21日", "definitions": { "title": "1. 服务定义", "content": "MyKello 提供美容服务预约代行平台，旨在促进用户与美容服务提供者之间的预约及沟通。" }, "benefits": { "title": "2. 会员优惠", "signup": "新用户注册成功后，即可获得 5% 折扣券。", "referral": "使用推荐码注册时，推荐人与被推荐人均可获得 5% 折扣券。" }, "refund_policy": { "title": "3. 取消与退款规定", "subtitle": "根据预约日期前的取消时间，退款比例如下：", "five_days": "5日前：100% 退款", "three_days": "3日前：90% 退款", "two_days": "2日前：70% 退款", "one_day": "1日前：50% 退款", "same_day": "当日或未到场 (No-show)：不予退款", "note": "最终退款处理可能因各店铺的政策而有所不同。" }, "liability": { "title": "4. 免责声明", "interpretation": "「实时通译」功能为提供用户便利的辅助工具。公司对因翻译不准确而导致的预约错误或纠纷不承担责任。", "community": "公司对通过社区功能进行的用户间自发性线下聚会或个人交易中产生的损害、事故或纠纷不承担责任。" } }
  },
  "zh-TW": {
    "privacy_policy": { "title": "隱私政策", "effective_date": "生效日期：2024年4月21日", "table": { "category": "項目", "items": "收集資訊", "purpose": "收集目的", "retention": "保存期限" }, "collection": { "title": "1. 個人資訊的收集與使用", "required": "必填", "required_items": "姓名、電子郵件、預約資訊（日期、時間、店鋪、服務）、社交帳號登入ID", "required_purpose": "會員註冊、身份識別、提供服務（預約）、客戶諮詢", "auto": "自動收集", "auto_items": "IP 地址、Cookie、裝置資訊、服務使用紀錄", "auto_purpose": "提高服務品質及防止異常使用" }, "retention": { "title": "2. 保存及使用期限", "content": "原則上，個人資訊將保存至註銷會員為止。但根據相關法令規定有必要保存時，可在該期限內予以保存。", "legal_basis": "遵守相關法令（如《電子商務法》等）" }, "third_party": { "title": "3. 向第三方提供個人資訊", "content": "MyKello 為提供服務，向以下合作夥伴提供個人資訊。", "providers": "Supabase（資料庫）、Google（身份驗證）、X（身份驗證）" }, "overseas": { "title": "4. 個人資訊跨境傳輸", "recipient": "接收方", "country": "國家", "purpose": "傳輸目的", "items": "傳輸項目", "supabase_name": "Supabase Inc.", "google_name": "Google LLC", "usa": "美國", "storage_auth": "資料儲存及用戶身份驗證 (OAuth 2.0)", "log_items": "電子郵件、個人資料資訊、服務使用日誌" }, "destruction": { "title": "5. 銷毀程序及方法", "content": "個人資訊在達到使用目的後將立即銷毀。電子文件將透過無法還原的技术方法進行刪除。" } },
    "signup_consent": { "all_agree": "我同意所有條款。", "privacy_required": "[必填] 同意收集並使用個人資訊", "privacy_optional": "[可選] 同意接收行銷資訊", "view_detail": "查看詳情", "terms_required": "[必填] 同意服務條款" },
    "terms_of_service": { "title": "服務條款", "effective_date": "生效日期：2024年4月21日", "definitions": { "title": "1. 服務定義", "content": "MyKello 提供美容服務預約代行平台，旨在促進用戶與美容服務提供者之間的預約及溝通。" }, "benefits": { "title": "2. 會員優惠", "signup": "新用戶註冊成功後，即可獲得 5% 折扣券。", "referral": "使用推薦碼註冊時，推薦人與被推薦人均可獲得 5% 折扣券。" }, "refund_policy": { "title": "3. 取消與退款規定", "subtitle": "根據預約日期前的取消時間，退款比例如下：", "five_days": "5日前：100% 退款", "three_days": "3日前：90% 退款", "two_days": "2日前：70% 退款", "one_day": "1日前：50% 退款", "same_day": "當日或未到場 (No-show)：不予退款", "note": "最終退款處理可能因各店鋪的政策而有所不同。" }, "liability": { "title": "4. 免責聲明", "interpretation": "「實時通譯」功能為提供用戶便利的輔助工具。公司對因翻譯不準確而導致的預約錯誤或糾紛不承擔責任。", "community": "公司對透過社區功能進行的用户間自發性線下聚會或個人交易中產生的損害、事故或糾紛不承擔責任。" } }
  }
};

const locales = Object.keys(translations);

locales.forEach(l => {
    const f = `public/locales/${l}/common.json`;
    try {
        let content = fs.readFileSync(f, 'utf8');
        let obj = JSON.parse(content);
        
        // Safety: ensure we are merging into a clean object
        Object.assign(obj, translations[l]);
        
        fs.writeFileSync(f, JSON.stringify(obj, null, 2), 'utf8');
        console.log(l, "OK");
    } catch (e) {
        console.error(l, "FAIL", e.message);
    }
});
